"""Parsing helpers for the legacy 0886.sqlite3 data (all columns are TEXT)."""

import ast
import datetime
import logging
import re
from decimal import Decimal, InvalidOperation


def parse_br_decimal(value):
    """'1.234,56' or 'R$1.234,56 C' -> Decimal('1234.56'). Returns None for blank/invalid input."""
    if value is None:
        return None
    value = str(value).strip()
    if not value:
        return None
    # Mantém apenas dígitos, vírgula, ponto e sinal de menos
    limpo = re.sub(r"[^\d,.\-]", "", value)
    if not limpo:
        return None
    limpo = limpo.replace(".", "").replace(",", ".")
    try:
        return Decimal(limpo)
    except InvalidOperation:
        return None


def parse_br_date(value):
    """'dd/mm/aaaa' -> date. Returns None for blank/invalid input."""
    if not value:
        return None
    value = str(value).strip()
    if not value:
        return None
    try:
        return datetime.datetime.strptime(value, "%d/%m/%Y").date()
    except ValueError:
        return None


def parse_int(value):
    if value is None:
        return None
    value = str(value).strip()
    if not value:
        return None
    try:
        return int(value)
    except ValueError:
        # Some legacy "atraso"/count columns can carry non-numeric text; be safe.
        digits = re.sub(r"[^0-9-]", "", value)
        return int(digits) if digits else None


def parse_py_list(value):
    """Legacy columns store repr() of a Python list, e.g. "['67999755980']".

    ast.literal_eval is safe here (no arbitrary code execution) because the
    source data is machine-generated by the legacy export, not raw external
    user input.
    """
    if not value:
        return []
    value = str(value).strip()
    if not value:
        return []
    try:
        result = ast.literal_eval(value)
    except (ValueError, SyntaxError):
        return []
    if isinstance(result, (list, tuple)):
        return [str(x).strip() for x in result if str(x).strip()]
    return []


def normalize_phone_br(raw):
    """'67999755980' -> '+5567999755980' (assumes Brazilian local numbers).

    Returns None if the input doesn't look like a plausible BR phone number.
    """
    if not raw:
        return None
    digits = re.sub(r"\D", "", str(raw))
    if not digits:
        return None
    if digits.startswith("00"):
        digits = digits[2:]
    if digits.startswith("55") and len(digits) in (12, 13):
        # already has country code
        return f"+{digits}"
    if len(digits) in (10, 11):
        # DDD (2) + 8 or 9 digit number
        return f"+55{digits}"
    if len(digits) in (12, 13) and digits.startswith("55"):
        return f"+{digits}"
    # Fallback: keep whatever digits we have, prefixed with +55, best-effort.
    if 8 <= len(digits) <= 13:
        return f"+55{digits}" if not digits.startswith("55") else f"+{digits}"
    return None


def validar_cpf(cpf: str) -> bool:
    """Valida um CPF brasileiro (algoritmo oficial dos dígitos verificadores).

    Aceita formatos com pontuação ("123.456.789-09") ou somente dígitos.
    Retorna False para tamanho errado, todos-iguais ou dígitos verificadores
    inválidos. Nunca levanta.
    """
    if not cpf:
        return False
    digits = re.sub(r"\D", "", str(cpf))
    if len(digits) != 11:
        return False
    if digits == digits[0] * 11:
        return False
    try:
        d1 = sum(int(digits[i]) * (10 - i) for i in range(9))
        d1 = (d1 * 10) % 11 % 10
        if d1 != int(digits[9]):
            return False
        d2 = sum(int(digits[i]) * (11 - i) for i in range(10))
        d2 = (d2 * 10) % 11 % 10
        if d2 != int(digits[10]):
            return False
        return True
    except (ValueError, IndexError):
        return False


def normalizar_cpf(cpf: str) -> str:
    """Reduz um CPF a 11 dígitos. Retorna '' se não houver 11 dígitos."""
    if not cpf:
        return ""
    digits = re.sub(r"\D", "", str(cpf))
    return digits if len(digits) == 11 else ""


def formatar_cpf_pontuado(cpf: str) -> str:
    """Retorna o CPF no formato 000.000.000-00 se tiver 11 dígitos.
    Caso contrário, retorna o CPF limpo (somente dígitos).
    """
    clean = normalizar_cpf(cpf)
    if len(clean) == 11:
        return f"{clean[:3]}.{clean[3:6]}.{clean[6:9]}-{clean[9:]}"
    return clean


def parse_nome_salvo(nome: str):
    """Extrai (cpf, nome) de um contato salvo no padrão PHN_<cpf>_<nome>.

    Retorna (None, None) se o nome não seguir o padrão de cliente. O CPF
    retornado são 11 dígitos (não formatado). O nome é o restante após o CPF,
    podendo conter espaços.
    """
    if not nome:
        return (None, None)
    nome = str(nome).strip()
    if not nome.upper().startswith("PHN_"):
        return (None, None)
    rest = nome[4:]
    m = re.match(r"\s*(\d{11})\s*_?\s*(.*)", rest)
    if not m:
        return (None, None)
    return (m.group(1), m.group(2).strip())


def normalizar_cpfs_clientes(
    connection, cliente_model, telefone_model, contrato_model, conversa_model, logger=None
):
    """Renomeia `Cliente.cpf` (chave primária) para a forma normalizada (11
    dígitos), atualizando em cascata as FKs de `telefone_model`,
    `contrato_model` e `conversa_model` que apontam para o cliente.

    Usa SQL bruto com checagem de FK temporariamente desligada (MySQL:
    `SET FOREIGN_KEY_CHECKS`; SQLite: `PRAGMA foreign_keys`) porque alterar o
    valor de uma primary key via `Model.save()` do Django não faz UPDATE —
    cria uma linha nova e deixa as FKs das linhas filhas órfãs.

    Colisões — dois CPFs distintos que normalizam para o mesmo valor, ou um
    CPF que normaliza para um valor já usado por outro cliente que
    permanece como está — são logadas como warning e **não são alteradas**,
    para não violar a constraint de chave primária.

    Aceita tanto os modelos "reais" (`core.models`) quanto os modelos
    históricos de uma migração (`apps.get_model(...)`), pois só usa `_meta`
    e o manager `.objects`, presentes em ambos.

    Retorna {"renomeados": int, "colisoes": int}.
    """
    log = logger or logging.getLogger(__name__)

    existing_cpfs = list(cliente_model.objects.values_list("cpf", flat=True).iterator())
    existing_set = set(existing_cpfs)

    renames = {}
    for cpf in existing_cpfs:
        clean = normalizar_cpf(cpf)
        if not clean or clean == cpf:
            continue
        renames[cpf] = clean

    if not renames:
        return {"renomeados": 0, "colisoes": 0}

    target_counts = {}
    for old, new in renames.items():
        target_counts.setdefault(new, []).append(old)

    to_apply = {}
    colisoes = 0
    for new, olds in target_counts.items():
        # Colide com outro cpf que normaliza para o mesmo valor, ou com um
        # cpf já limpo (que não está sendo renomeado) igual ao destino.
        blocked_by_existing = new in existing_set and new not in renames
        if len(olds) > 1 or blocked_by_existing:
            colisoes += len(olds)
            for old in olds:
                log.warning(
                    "normalizar_cpf: colisão ao normalizar cliente cpf=%r -> %r; "
                    "mantendo original sem alterar.",
                    old,
                    new,
                )
            continue
        to_apply[olds[0]] = new

    if not to_apply:
        return {"renomeados": 0, "colisoes": colisoes}

    cliente_table = cliente_model._meta.db_table
    related_specs = [
        (telefone_model._meta.db_table, telefone_model._meta.get_field("cliente").column),
        (contrato_model._meta.db_table, contrato_model._meta.get_field("cliente").column),
        (conversa_model._meta.db_table, conversa_model._meta.get_field("cliente").column),
    ]

    vendor = connection.vendor
    with connection.cursor() as cursor:
        if vendor == "mysql":
            cursor.execute("SET FOREIGN_KEY_CHECKS=0")
        elif vendor == "sqlite":
            cursor.execute("PRAGMA foreign_keys=OFF")
        try:
            for old, new in to_apply.items():
                for table, column in related_specs:
                    cursor.execute(
                        f"UPDATE {table} SET {column} = %s WHERE {column} = %s",
                        [new, old],
                    )
                cursor.execute(
                    f"UPDATE {cliente_table} SET cpf = %s WHERE cpf = %s",
                    [new, old],
                )
        finally:
            if vendor == "mysql":
                cursor.execute("SET FOREIGN_KEY_CHECKS=1")
            elif vendor == "sqlite":
                cursor.execute("PRAGMA foreign_keys=ON")

    return {"renomeados": len(to_apply), "colisoes": colisoes}
