# Generated by Django 5.2.15 on 2026-07-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_botconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bloqueado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='bloqueado_ia',
            field=models.BooleanField(default=False, help_text='Se marcado, o bot nunca responde automaticamente a este cliente.'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='bloqueado_motivo',
            field=models.TextField(blank=True),
        ),
    ]
