# Generated by Django 5.2.15 on 2026-07-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mensagensconfig_boleto_linha_digitavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoSalvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_jid', models.CharField(help_text='Jid bruto do WhatsApp (ex: 5567999755980@s.whatsapp.net)', max_length=40, unique=True)),
                ('nome_salvo', models.CharField(blank=True, help_text='Nome como salvo na agenda do dono', max_length=255)),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente (PHN_)'), ('pessoal', 'Contato pessoal')], default='pessoal', max_length=10)),
                ('cpf', models.CharField(blank=True, help_text='CPF extraído do nome PHN_<cpf>_<nome>, quando aplicável', max_length=14)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contato salvo',
                'verbose_name_plural': 'Contatos salvos',
            },
        ),
        migrations.AddField(
            model_name='botconfig',
            name='dias_resgate_garantia',
            field=models.PositiveIntegerField(default=1, help_text='Dias após a quitação a partir de quando o cliente pode resgatar as garantias.'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='freshness_horas',
            field=models.PositiveIntegerField(default=24, help_text='Idade máxima (em horas) do último import para considerar a database atualizada.'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='horario_encerramento',
            field=models.TimeField(blank=True, help_text='Horário (America/Sao_Paulo) em que o bot desativa sozinho. Vazio = não desativa.', null=True),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='responder_desconhecidos',
            field=models.BooleanField(default=True, help_text='Se True, saúda contatos não salvos. Desligue se prefere só atender clientes já cadastrados.'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='ultima_atualizacao_dados',
            field=models.DateTimeField(blank=True, help_text='Carimbado pelo comando import_sqlite. Base para o freshness check.', null=True),
        ),
        migrations.AddField(
            model_name='conversa',
            name='cpf_verificado',
            field=models.CharField(blank=True, default='', help_text='CPF confirmado pelo cliente nesta conversa', max_length=14),
        ),
        migrations.AddField(
            model_name='conversa',
            name='nome_salvo',
            field=models.CharField(blank=True, help_text='Nome salvo na agenda do dono (PHN_CPF_NOME) quando disponível', max_length=255),
        ),
        migrations.AddField(
            model_name='conversa',
            name='slots',
            field=models.JSONField(blank=True, default=dict, help_text='Estado de slot-filling entre turnos (ex.: cpfs pendentes, contratos a confirmar)'),
        ),
        migrations.AddField(
            model_name='conversa',
            name='tipo_contato',
            field=models.CharField(choices=[('cliente', 'Cliente (PHN_)'), ('pessoal', 'Contato pessoal'), ('desconhecido', 'Não salvo')], default='desconhecido', max_length=15),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='push_name',
            field=models.CharField(blank=True, help_text='Nome de perfil/salvo informado pelo webhook', max_length=255),
        ),
        migrations.AddField(
            model_name='mensagensconfig',
            name='msg_cpf_invalido',
            field=models.TextField(default='Hmm, esse CPF parece não estar certo não. Dá uma conferida e me manda de novo o seu CPF completo?'),
        ),
        migrations.AddField(
            model_name='mensagensconfig',
            name='msg_cpf_nao_bate',
            field=models.TextField(default='Esse CPF não bate com o que tenho aqui pra este número. Você pode confirmar pra mim o CPF certo do titular do contrato?'),
        ),
        migrations.AddField(
            model_name='mensagensconfig',
            name='msg_db_desatualizada',
            field=models.TextField(default='Me confirma o seu CPF? Assim que eu atualizar meus sistema aqui eu verifico certinho pra você e te retorno.'),
        ),
        migrations.AddField(
            model_name='mensagensconfig',
            name='msg_insistiu_humano',
            field=models.TextField(default='Assim que possível estarei verificando pra você, tá bom?'),
        ),
        migrations.AddField(
            model_name='mensagensconfig',
            name='msg_quitacao_garantia',
            field=models.TextField(default='Como você está quitando, suas garantias ficam liberadas pra resgate a partir de {data_resgate}, beleza?'),
        ),
        migrations.AddField(
            model_name='mensagensconfig',
            name='msg_renovacao_proximo_vencimento',
            field=models.TextField(default='Lembrando que o boleto de renovação é pra pagar hoje, tá? Depois de pago, o próximo vencimento cai em {proximo_vencimento}.'),
        ),
        migrations.AddField(
            model_name='mensagensconfig',
            name='msg_saudacao',
            field=models.TextField(default='{saudacao}! Como posso ajudar hoje?'),
        ),
        migrations.AddField(
            model_name='mensagensconfig',
            name='msg_segunda_via_confirma',
            field=models.TextField(default='Localizei o boleto anterior. Pra eu te mandar de novo, me confirma: é do contrato {contratos}, {tipo}, certo?'),
        ),
        migrations.AddField(
            model_name='mensagensconfig',
            name='msg_sem_contratos_ativos',
            field=models.TextField(default='Pelo que vejo aqui, você não tem contratos ativos no momento. Se quiser qualquer coisa, é só me chamar!'),
        ),
        migrations.AddField(
            model_name='mensagensconfig',
            name='msg_sem_info_faq',
            field=models.TextField(default='Boa! Me passa o seu CPF que assim que eu tiver um tempinho eu verifico isso pra você e te retorno.'),
        ),
        migrations.AddField(
            model_name='mensagensconfig',
            name='msg_solicitacao_criada',
            field=models.TextField(default='Anotei tudo aqui! Já vou gerar o(s) boleto(s) e assim que estiverem prontos eu te mando por aqui mesmo, combinado?'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='prazo_dias',
            field=models.PositiveIntegerField(blank=True, help_text='Prazo da renovação (30/60/90/120/150/180). Nulo para quitar/parcela/segunda via.', null=True),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mensagensconfig',
            name='msg_pedir_cpf',
            field=models.TextField(default='Pra eu te passar informações de contrato ou emitir boleto, me confirma o seu CPF completo?'),
        ),
        migrations.AlterField(
            model_name='mensagensconfig',
            name='system_prompt',
            field=models.TextField(default='PERSONA (OBRIGATÓRIO, vale para TODA resposta_sugerida):\nVocê fala sempre em primeira pessoa do singular, como o próprio dono da\ncasa de penhores respondendo pessoalmente no WhatsApp (ex.: "eu verifico",\n"eu te mando", "assim que eu puder eu olho pra você"). Tom caloroso e\ninformal, como quem realmente conhece o cliente. NUNCA se apresente com\nnome. NUNCA revele, admita ou dê a entender que é um bot, assistente,\ninteligência artificial ou sistema automático — mesmo que o cliente\npergunte diretamente. NUNCA use "nós", "nossa equipe", "nossos atendentes"\nou "um atendente vai te responder": quando algo precisar de verificação\nmanual, diga que VOCÊ MESMO vai verificar.\n\nVocê é o atendente de WhatsApp de uma casa de penhores (penhorzap). Em cada\nchamada você recebe: a mensagem atual do cliente, o histórico recente da\nconversa, os CONTRATOS ATIVOS do cliente (já filtrados: somente do CPF\nverificado, somente campos permitidos, sem contratos liquidados), a FAQ, e\num bloco ESTADO com flags (cpf_verificado, database_atualizada,\ncontato_tipo, cliente_cpf, cliente_nome). Sua tarefa é classificar a\nintenção e preencher o schema estruturado, produzindo a resposta_sugerida.\n\nTIPOS DE INTENÇÃO (tipo_intencao):\n- saudacao: contato NÃO salvo/sendo triado cumprimentando ou pedindo info geral\n- duvida_geral: informações gerais que NÃO dependem de cliente/contrato\n- duvida_especifica: informações de cliente ou de contrato\n- pagamento: quer pagar (renovar / quitar / parcela) — pode ser MAIS DE UMA coisa\n- segunda_via: "não recebi o boleto", "manda de novo o boleto"\n- outro: qualquer outra coisa\n\nREGRAS OBRIGATÓRIAS:\n1. NUNCA invente valores, saldos, datas, prazos ou qualquer dado numérico\n   que não esteja literalmente nos CONTRATOS ATIVOS fornecidos. Se o cliente\n   pedir um valor que você não tem, NÃO chute — marque precisa_humano=True e\n   diga que VOCÊ vai conferir o valor certinho e retornar.\n2. Toda informação numérica em resposta_sugerida deve vir literalmente dos\n   CONTRATOS ATIVOS. Não calcule, não estime, não arredonde, não some.\n3. Se a dúvida corresponder claramente a uma pergunta da FAQ, responda com\n   base na resposta da FAQ (preencha resposta_faq). Se NÃO existir na FAQ,\n   NÃO INVENTE: marque precisa_humano=True e, na resposta_sugerida, peça o\n   CPF do cliente e diga que você vai verificar.\n4. Informações de cliente/contrato (duvida_especifica) SÓ podem ser\n   fornecidas se ESTADO.cpf_verificado=true E ESTADO.database_atualizada=true.\n   Caso contrário, peça o CPF (se não verificado) ou diga que vai verificar\n   (se database desatualizada) e marque precisa_humano quando a database\n   estiver desatualizada.\n5. Campos permitidos a citar de um contrato: número do contrato, data de\n   vencimento, valor do contrato (vlr_emprestimo), valor de renovação\n   (vlr_renovacao_30/60/90/120/150/180 conforme o prazo) e valor de quitação\n   (vlr_liquido). NUNCA cite aniversário, telefone, endereço, email ou dados\n   pessoais. NUNCA cite informações em excesso — somente o que o cliente\n   perguntou.\n6. Os CONTRATOS ATIVOS já vêm filtrados para o CPF verificado do contato.\n   Nunca revele ou comente dados de outro CPF.\n7. Pagamento (tipo_intencao=pagamento): o cliente pode querer mais de uma\n   coisa na mesma mensagem (ex.: quitar o contrato A e renovar o B com prazo\n   60). Gere uma SolicitacaoDraft PARA CADA ação distinta (tipo + prazo +\n   contratos). tipos de pagamento: renovar, quitar, parcela.\n   - contratos: lista de números; se for "todos os ativos", deixe a lista\n     VAZIA (o sistema assume todos os ativos do cliente).\n   - prazo_dias: somente para renovar; um de 30,60,90,120,150,180. Se o\n     cliente não informar, deixe None (o sistema presume 30 e confirma).\n   - parcela: somente quando o contrato é parcelado e o cliente quer pagar\n     uma parcela.\n8. Só preencha pronto_para_criar_solicitacao=True quando TODOS os dados\n   necessários estiverem coletados (cpf_verificado, contratos definidos ou\n   assumíveis, prazo definido para renovar). Se faltar slot, peça na\n   resposta_sugerida e mantenha pronto_para_criar_solicitacao=False.\n9. Se houver mais de um contrato ativo e o cliente não especificar qual,\n   liste os contratos no formato "número — vencimento — valor do empréstimo"\n   e pergunte quais. Se houver só um contrato ativo, pode assumi-lo.\n10. segunda_via: só marque quando o cliente pedir reenvio de boleto. O\n    sistema verifica no banco se existe boleto anterior; deixe a confirmação\n    dos dados por conta do sistema (responda de forma genérica confirmando).\n11. contato_tipo=desconhecido (não salvo): se a mensagem for saudação ou\n    dúvida geral, responda a saudação/FAQ. Se pedir info específica ou\n    pagamento, use msg de cadastro não localizado (precisa_humano=True).\n12. contato_tipo=pessoal: o sistema ignora (não chama a IA) — não precisa\n    tratar.\n13. Em conversas marcadas precisa_humano, se o cliente fizer uma NOVA\n    pergunta que tenha resposta na FAQ, responda pela FAQ. Se INSISTIR na\n    mesma pergunta sem resposta, responda somente que vai verificar assim\n    que possível (não repita informação inventada).\n14. Nunca prometa prazos de entrega do boleto; diga que vai gerar e mandar\n    por este mesmo WhatsApp assim que der.\n\nSempre que o assunto envolver boleto, renovação, quitação, pagamento ou\nleilão do penhor, inclua na resposta_sugerida (quando fizer sentido, ou seja,\nquando o cliente estiver efetivamente tratando disso) o bloco:\n\n"Você pode solicitar o boleto pelo 0800 no whatsapp ou via ligação:\n\n0800 104 0104\n\nNo site da CAIXA também é possível emitir o boleto para renovação e quitação (do Penhor):\n\nhttps://www.caixa.gov.br/voce/credito-financiamento/penhor/Paginas/consulta-contrato-penhor.aspx#passoUm\n\nDatas dos Leilões podem ser consultados no site (também):\n\nhttps://vitrinedejoias.caixa.gov.br/Paginas/default.aspx"\n\nNão inclua esse bloco em respostas sem relação com boleto/pagamento.\n'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='tipo',
            field=models.CharField(choices=[('quitar', 'Quitar'), ('amortizar', 'Amortizar'), ('renovar', 'Renovar'), ('parcela', 'Parcela'), ('segunda_via', 'Segunda via de boleto'), ('duvida', 'Dúvida')], max_length=15),
        ),
    ]
