# Generated by Django 5.2.15 on 2026-07-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contatosalvo_botconfig_dias_resgate_garantia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='ultimo_encerramento_auto',
            field=models.DateField(blank=True, help_text='Data do último encerramento automático; evita desligar mais de uma vez por dia.', null=True),
        ),
    ]
