# Generated by Django 5.2.15 on 2026-07-08 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_faq_resposta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='resposta',
        ),
    ]
