# Generated by Django 5.2.15 on 2026-07-11 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_faq_resposta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportDataJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='import_sqlite/', verbose_name='Arquivo SQLite')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Em andamento'), ('concluido', 'Concluído'), ('falhou', 'Falhou')], default='pendente', max_length=20, verbose_name='Status')),
                ('counts', models.JSONField(blank=True, default=dict, verbose_name='Contagens')),
                ('erro', models.TextField(blank=True, default='', verbose_name='Erro')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('finalizado_em', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Importação de dados',
                'verbose_name_plural': 'Importações de dados',
                'ordering': ['-criado_em'],
            },
        ),
    ]
