# Generated by Django 5.2.15 on 2026-07-15 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_importdatajob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversa',
            name='identificacao',
            field=models.CharField(choices=[('nenhum', 'Não identificado'), ('telefone', 'Telefone cadastrado'), ('cpf', 'CPF digitado')], default='nenhum', help_text='Como o contato foi identificado nesta conversa: telefone cadastrado (não expira) ou CPF digitado (expira em 24h).', max_length=10),
        ),
        migrations.AddField(
            model_name='conversa',
            name='processando_desde',
            field=models.DateTimeField(blank=True, help_text='Mutex leve: carimbado quando process_mensagem começa a processar esta conversa, limpo ao final.', null=True),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='arquivo',
            field=models.FileField(blank=True, help_text='Anexo enviado pelo operador (mensagens OUT).', null=True, upload_to='conversa_arquivos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='enviado_ok',
            field=models.BooleanField(blank=True, help_text='OUT: resultado do envio via Evolution. None = mensagem IN ou registro legado.', null=True),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='tipo_midia',
            field=models.CharField(blank=True, choices=[('image', 'Imagem'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('document', 'Documento')], default='', help_text='Vazio = sem mídia. Preenchido a partir do payload da Evolution (IN) ou pelo operador (OUT).', max_length=10),
        ),
        migrations.AddField(
            model_name='mensagensconfig',
            name='msg_fallback_sem_resposta',
            field=models.TextField(default='Boa pergunta! Deixa eu verificar com calma e já te retorno por aqui mesmo, combinado?'),
        ),
        migrations.AddField(
            model_name='mensagensconfig',
            name='msg_info_negada_desconhecido',
            field=models.TextField(default='Por segurança, as informações do seu contrato constam no próprio boleto. Quer que eu gere o boleto pra você?'),
        ),
        migrations.AddField(
            model_name='mensagensconfig',
            name='msg_midia_nao_suportada',
            field=models.TextField(default='Recebi seu áudio/vídeo, mas por aqui eu só consigo ler mensagens de texto 🙏 Pode escrever sua dúvida que um atendente vai te responder?'),
        ),
        migrations.AddField(
            model_name='mensagensconfig',
            name='tpl_contrato_parcela',
            field=models.TextField(default='💳 Contrato {contrato}: valor da parcela = {valor_parcela}.'),
        ),
        migrations.AddField(
            model_name='mensagensconfig',
            name='tpl_contrato_quitacao',
            field=models.TextField(default='✅ Contrato {contrato}: valor para quitação = {valor_quitacao} (vencimento: {vencimento}).'),
        ),
        migrations.AddField(
            model_name='mensagensconfig',
            name='tpl_contrato_renovacao',
            field=models.TextField(default='🔄 Contrato {contrato}: renovação por {prazo_dias} dias = {valor_renovacao} (vencimento atual: {vencimento}).'),
        ),
        migrations.AddField(
            model_name='mensagensconfig',
            name='tpl_contrato_resumo',
            field=models.TextField(default='📄 Contrato {contrato} — vencimento {vencimento} — valor do empréstimo {valor_emprestimo}.'),
        ),
        migrations.AddField(
            model_name='mensagensconfig',
            name='tpl_contrato_vencimento',
            field=models.TextField(default='📄 Contrato {contrato}: vencimento em {vencimento}.'),
        ),
        migrations.AddField(
            model_name='mensagensconfig',
            name='tpl_lista_footer',
            field=models.TextField(default='Se precisar de mais alguma informação, é só falar!'),
        ),
        migrations.AddField(
            model_name='mensagensconfig',
            name='tpl_lista_header',
            field=models.TextField(default='{nome}, você tem {qtd} contrato(s) ativo(s):'),
        ),
        migrations.AddField(
            model_name='mensagensconfig',
            name='tpl_saudacao_cliente',
            field=models.TextField(default='{saudacao}, {nome}! 😊 Aqui é o atendimento da PenhorZap. Como posso te ajudar?'),
        ),
        migrations.CreateModel(
            name='FAQSugerida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(help_text='Pergunta resumida sugerida pela IA', max_length=255)),
                ('pergunta_original', models.TextField(blank=True, help_text='Mensagem literal do cliente')),
                ('ocorrencias', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=10)),
                ('revisado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conversa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs_sugeridas', to='core.conversa')),
                ('faq_criada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.faq')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FAQ sugerida',
                'verbose_name_plural': 'FAQs sugeridas',
                'ordering': ['-ocorrencias', '-criado_em'],
            },
        ),
    ]
