# Generated by Django 5.2.15 on 2026-07-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_normalizar_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagensconfig',
            name='tpl_totalizador',
            field=models.TextField(default='📊 Resumo: {qtd} contrato(s), total de {total}. Se precisar de mais alguma informação, é só falar!'),
        ),
        migrations.AddField(
            model_name='mensagensconfig',
            name='tpl_totalizador_sem_valor',
            field=models.TextField(default='São {qtd} contrato(s) ao todo. Se precisar de mais alguma informação, é só falar!'),
        ),
        migrations.AlterField(
            model_name='mensagensconfig',
            name='tpl_lista_footer',
            field=models.TextField(default='Se precisar de mais alguma informação, é só falar!', help_text='(não usado — fechamento incorporado ao totalizador)'),
        ),
    ]
