# Generated by Django 5.2.15 on 2026-07-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_update_system_prompt_indefinido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagensconfig',
            name='msg_insistiu_humano',
        ),
        migrations.RemoveField(
            model_name='mensagensconfig',
            name='msg_sem_info_faq',
        ),
        migrations.RemoveField(
            model_name='mensagensconfig',
            name='msg_verificacao_falhou',
        ),
        migrations.RemoveField(
            model_name='mensagensconfig',
            name='msg_verificacao_ok',
        ),
        migrations.RemoveField(
            model_name='mensagensconfig',
            name='tpl_lista_footer',
        ),
        migrations.AlterField(
            model_name='mensagensconfig',
            name='msg_boleto_intro',
            field=models.TextField(default='Prontinho, segue o boleto que você pediu. 😁👍 Logo abaixo te mando também o código de barras pra facilitar.'),
        ),
        migrations.AlterField(
            model_name='mensagensconfig',
            name='msg_cadastro_nao_localizado',
            field=models.TextField(default='Oi! Não achei seu número aqui no meu cadastro. Assim que eu tiver um tempinho eu verifico pra você e já te retorno.'),
        ),
        migrations.AlterField(
            model_name='mensagensconfig',
            name='msg_cpf_invalido',
            field=models.TextField(default='O CPF que vc me passou está inválido 🤦\u200d♂️ Dá uma conferida e me manda novamente por favor 😁🙏'),
        ),
        migrations.AlterField(
            model_name='mensagensconfig',
            name='msg_db_desatualizada',
            field=models.TextField(default='*Mensagem automática:* Oi. Estou ocupado no momento. Mas assim que eu tiver um tempinho eu te verifico pra vc. 🤝'),
        ),
        migrations.AlterField(
            model_name='mensagensconfig',
            name='msg_midia_nao_suportada',
            field=models.TextField(default='Recebi seu áudio/vídeo, mas por aqui eu só consigo ler mensagens de texto 🙏 Pode escrever sua dúvida que já te respondo.'),
        ),
        migrations.AlterField(
            model_name='mensagensconfig',
            name='msg_neutra_padrao',
            field=models.TextField(default='*Mensagem automática:* Oi. Estou ocupado no momento. Mas assim que eu tiver um tempinho eu te verifico pra vc. 🤝'),
        ),
        migrations.AlterField(
            model_name='mensagensconfig',
            name='msg_pedir_cpf',
            field=models.TextField(default='Me informe seu CPF por gentileza, que já verifico para você.'),
        ),
        migrations.AlterField(
            model_name='mensagensconfig',
            name='msg_quitacao_garantia',
            field=models.TextField(default='Pagando hoje o boleto, vc pode vir resgatar a partir de 📆{data_resgate} as 🕜11hrs.'),
        ),
        migrations.AlterField(
            model_name='mensagensconfig',
            name='msg_renovacao_proximo_vencimento',
            field=models.TextField(default='Lembrando que o boleto só vale para hoje, ok? Depois de pago, o próximo vencimento será {proximo_vencimento}.'),
        ),
        migrations.AlterField(
            model_name='mensagensconfig',
            name='msg_saudacao',
            field=models.TextField(default='{saudacao}! Como posso ajudar?'),
        ),
        migrations.AlterField(
            model_name='mensagensconfig',
            name='msg_sem_contratos_ativos',
            field=models.TextField(default='Pelo que verifiquei aqui no sistema vc não tem contratos ativos no momento.'),
        ),
        migrations.AlterField(
            model_name='mensagensconfig',
            name='msg_solicitacao_criada',
            field=models.TextField(default='Vou gerar o(s) boleto(s) e daqui a pouco eu te envio aqui mesmo.'),
        ),
        migrations.AlterField(
            model_name='mensagensconfig',
            name='tpl_contrato_parcela',
            field=models.TextField(default='📄 *Contrato*: {contrato}\n💰 Valor das parcelas: {valor_parcela}'),
        ),
        migrations.AlterField(
            model_name='mensagensconfig',
            name='tpl_contrato_quitacao',
            field=models.TextField(default='🔸Liquidação: {valor_quitacao}'),
        ),
        migrations.AlterField(
            model_name='mensagensconfig',
            name='tpl_contrato_renovacao',
            field=models.TextField(default='🔹Renovação {prazo_dias} dias: {valor_renovacao}'),
        ),
        migrations.AlterField(
            model_name='mensagensconfig',
            name='tpl_contrato_resumo',
            field=models.TextField(default='📄 *Contrato*: {contrato}\n🗓️ *Vencimento*: {vencimento}\n💰 *Empréstimo*: {valor_emprestimo}'),
        ),
        migrations.AlterField(
            model_name='mensagensconfig',
            name='tpl_contrato_vencimento',
            field=models.TextField(default='📄 *Contrato* {contrato}\n🗓️ *Vencimento*: {vencimento}.'),
        ),
        migrations.AlterField(
            model_name='mensagensconfig',
            name='tpl_saudacao_cliente',
            field=models.TextField(default='{saudacao}, {nome}! 😊 Como posso te ajudar?'),
        ),
    ]
