# Generated by Django 5.2.15 on 2026-07-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_mensagensconfig_tpl_contrato_laudo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='enviar_respostas_faq_ia',
            field=models.BooleanField(default=False, help_text='Se True, envia as respostas das FAQs ativas para a IA ter mais contexto do negócio antes de classificar a intenção.'),
        ),
    ]
