# Generated by Django 5.2.15 on 2026-07-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_botconfig_enviar_respostas_faq_ia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagensconfig',
            name='tpl_totalizador_sem_valor',
        ),
        migrations.AddField(
            model_name='mensagensconfig',
            name='tpl_totalizador_geral',
            field=models.TextField(default='📊 Resumo dos {qtd} contrato(s):\n💎 Total avaliado: {total_avaliacao}\n💰 Total emprestado: {total_emprestimo}{renovacoes}'),
        ),
        migrations.AlterField(
            model_name='mensagensconfig',
            name='tpl_contrato_laudo',
            field=models.TextField(default='📄 *Contrato*: {contrato}\n⚖️ *Peso*: {peso}\n💎 *Valor de avaliação*: {valor_avaliacao}\n📝 *Laudo/Garantia*: {laudo}'),
        ),
    ]
