# Generated by Django 5.2.15 on 2026-07-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_mesclar_infos_totalizador_geral'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagensconfig',
            name='msg_saudacao_com_pedido',
            field=models.TextField(default='{saudacao}!', help_text="Saudação quando a mesma mensagem já traz um pedido (não pergunta 'como posso ajudar' de novo)."),
        ),
        migrations.AddField(
            model_name='mensagensconfig',
            name='tpl_saudacao_cliente_com_pedido',
            field=models.TextField(default='{saudacao}, {nome}! 😊', help_text="Saudação quando a mesma mensagem já traz um pedido (não pergunta 'como posso te ajudar' de novo)."),
        ),
    ]
