# Generated by Django 5.2.15 on 2026-07-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_filtros_intro_resumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversa',
            name='remote_jid',
            field=models.CharField(help_text='Número bruto do WhatsApp', max_length=40, unique=True),
        ),
    ]
