# Generated by Django 5.2.15 on 2026-07-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_conversa_remote_jid'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='dados_recebidos',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
